# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmcp < Formula
  desc "BORIS MCP to CLI converter"
  homepage "https://github.com/sirob-tech/boris-mcp-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.1.0/bmcp-darwin-amd64.tar.gz"
      sha256 "5f9bd8bd2e5010365be0c99989884e3f0803365631560fe843f5f79034682a6b"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.1.0/bmcp-darwin-arm64.tar.gz"
      sha256 "7b7aa3f5c827d78442899b4213b5842f215a6dbc8420c2c02319df383ebe0478"

      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.1.0/bmcp-linux-amd64.tar.gz"
      sha256 "268cf675fad079468fe304a9f462e89895bb019768d61e7c91e67c4d9da61610"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirob-tech/boris-mcp-cli/releases/download/v0.1.0/bmcp-linux-arm64.tar.gz"
      sha256 "a01e58e4f6504228b6ffff3668dff3167e598df847043c54d0bd4c53bc8bba86"
      define_method(:install) do
        bin.install "bmcp"
      end
    end
  end

  test do
    system "#{bin}/bmcp", "version"
  end
end
